name: Renovate

on:
  workflow_dispatch:
  pull_request:
  schedule:
    # Weekly on Friday
    - cron: 0 0 * * 5

jobs:
  renovate:
    env:
      LOG_LEVEL: debug
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v6
      # TODO: Install missing system packages for python dependencies
      - run: |
          dnf install -y \
            libvirt-devel \
            krb5-devel \
            libpq-devel \
            redhat-rpm-config
      - name: Get GitHub App token
        id: token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.RENOVATE_BOT_APP_ID }}
          private-key: ${{ secrets.RENOVATE_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - uses: renovatebot/github-action@v44.2.0
        with:
          configurationFile: .github/renovate-config.json
          token: '${{ steps.token.outputs.token }}'
