name: Renovate

on:
  workflow_dispatch:
  schedule:
    # Weekly on Friday
    - cron: 0 0 * * 5

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      # TODO: Install missing system packages for python dependencies
      - uses: renovatebot/github-action@v44.2.0
        # TODO: Configure renovatebot
